f = open("file.txt", "r")
content = f.read()
lines = content.split("\n")
words = content.split()
characters = len(content)
print("Number of lines:", len(lines))
print("Number of words:", len(words)) 
print("Number of characters:", characters)
f.close()
